#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
#------------------------------------------------------------------------------

set -x

cd fiberOrientation
./Allwclean

cd ../myPimpleFoam
wclean


#------------------------------------------------------------------------------
